/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author franc
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form registroUsuarios
     */
    public Estadisticas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nivel1 = new javax.swing.JLabel();
        Nivel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLiga = new javax.swing.JTextField();
        txtBG = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        txtBE = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 560));
        setUndecorated(true);
        setOpacity(0.92F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntos adquiridos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Batallas empatadas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Batallas perdidas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estadisticas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Nivel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Nivel1.setForeground(new java.awt.Color(255, 255, 255));
        Nivel1.setText("Liga Actual");
        getContentPane().add(Nivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        Nivel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Nivel.setForeground(new java.awt.Color(255, 255, 255));
        Nivel.setText("Nivel");
        getContentPane().add(Nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Batallas ganadas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtLiga.setEditable(false);
        txtLiga.setBackground(new java.awt.Color(64, 239, 175));
        txtLiga.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtLiga.setForeground(new java.awt.Color(255, 255, 255));
        txtLiga.setBorder(null);
        getContentPane().add(txtLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 220, 35));

        txtBG.setEditable(false);
        txtBG.setBackground(new java.awt.Color(64, 239, 175));
        txtBG.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtBG.setForeground(new java.awt.Color(255, 255, 255));
        txtBG.setBorder(null);
        getContentPane().add(txtBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 35));

        txtNivel.setEditable(false);
        txtNivel.setBackground(new java.awt.Color(64, 239, 175));
        txtNivel.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtNivel.setForeground(new java.awt.Color(255, 255, 255));
        txtNivel.setBorder(null);
        getContentPane().add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 220, 35));

        txtPA.setEditable(false);
        txtPA.setBackground(new java.awt.Color(64, 239, 175));
        txtPA.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtPA.setForeground(new java.awt.Color(255, 255, 255));
        txtPA.setBorder(null);
        getContentPane().add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 220, 35));

        txtBE.setEditable(false);
        txtBE.setBackground(new java.awt.Color(64, 239, 175));
        txtBE.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtBE.setForeground(new java.awt.Color(255, 255, 255));
        txtBE.setBorder(null);
        getContentPane().add(txtBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 35));

        txtBP.setEditable(false);
        txtBP.setBackground(new java.awt.Color(64, 239, 175));
        txtBP.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtBP.setForeground(new java.awt.Color(255, 255, 255));
        txtBP.setBorder(null);
        txtBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBPActionPerformed(evt);
            }
        });
        getContentPane().add(txtBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 220, 35));

        btnRegresar.setBackground(new java.awt.Color(79, 224, 66));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 130, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 220, 3));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setOpaque(true);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, 3));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator3.setOpaque(true);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 220, 3));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator4.setOpaque(true);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 220, 3));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator5.setOpaque(true);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 220, 3));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(64, 239, 175));
        jSeparator6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator6.setOpaque(true);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 3));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconfinder-gymfightpunchboxing-glovessports-and-competitionboxingathleteolympictrainingglovessport-4394759_119509.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 256, 256));

        btnCerrar.setBackground(new java.awt.Color(79, 224, 66));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 40));

        jLabel6.setBackground(new java.awt.Color(64, 239, 175));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nivel;
    private javax.swing.JLabel Nivel1;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField txtBE;
    public javax.swing.JTextField txtBG;
    public javax.swing.JTextField txtBP;
    public javax.swing.JTextField txtLiga;
    public javax.swing.JTextField txtNivel;
    public javax.swing.JTextField txtPA;
    // End of variables declaration//GEN-END:variables
}
