/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author ESTEBAN SG
 */
public class FormCarta extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCarta
     */
    public FormCarta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAtaque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDefensa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMana = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textADesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(0, 204, 153));
        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 201, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtTipo.setEditable(false);
        txtTipo.setBackground(new java.awt.Color(0, 204, 153));
        txtTipo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setBorder(null);
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 201, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        txtAtaque.setEditable(false);
        txtAtaque.setBackground(new java.awt.Color(0, 204, 153));
        txtAtaque.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtAtaque.setForeground(new java.awt.Color(255, 255, 255));
        txtAtaque.setBorder(null);
        jPanel1.add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 95, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ataque");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 141, -1, -1));

        txtDefensa.setEditable(false);
        txtDefensa.setBackground(new java.awt.Color(0, 204, 153));
        txtDefensa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDefensa.setForeground(new java.awt.Color(255, 255, 255));
        txtDefensa.setBorder(null);
        jPanel1.add(txtDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 95, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Defensa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtMana.setEditable(false);
        txtMana.setBackground(new java.awt.Color(0, 204, 153));
        txtMana.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtMana.setForeground(new java.awt.Color(255, 255, 255));
        txtMana.setBorder(null);
        jPanel1.add(txtMana, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 95, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mana");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(51, 255, 51));
        btnRegresar.setText("R");
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 50, 40));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        textADesc.setEditable(false);
        textADesc.setBackground(new java.awt.Color(84, 170, 248));
        textADesc.setColumns(20);
        textADesc.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textADesc.setForeground(new java.awt.Color(255, 255, 255));
        textADesc.setLineWrap(true);
        textADesc.setRows(5);
        textADesc.setWrapStyleWord(true);
        textADesc.setBorder(null);
        textADesc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane1.setViewportView(textADesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 250, 130));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kracken.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 165, 210));

        btnCerrar.setBackground(new java.awt.Color(255, 102, 51));
        btnCerrar.setText("X");
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCarta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea textADesc;
    public javax.swing.JTextField txtAtaque;
    public javax.swing.JTextField txtDefensa;
    public javax.swing.JTextField txtMana;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
